In [4]:
import numpy as np

### **Basic Array Creation**

In [5]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [7]:
# Array stores only similar datatype
a=[1,2,'Hello',4.5,7.9]
np.array(a)
# Here all data are converted to One data type Note-: in this case to string.

array(['1', '2', 'Hello', '4.5', '7.9'], dtype='<U32')

In [8]:
a=[1,2,3,4]
np.array(a)

array([1, 2, 3, 4])

In [9]:
b=[1,5,2.0,9]
np.array(b)

array([1., 5., 2., 9.])

In [10]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l
# these are vectors means one dimensional

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l)
# these are matrix two dimensional

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### **Array Generation Function**

In [12]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [13]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
arr=np.zeros((3,5))
arr
# Similarly we can write np.ones()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [16]:
arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [17]:
arr=np.linspace(1,2,20)
arr

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

### **Random Generation Function**

In [18]:
np.random.rand(6)
# rand generates number in between 0 & 1.

array([0.8702618 , 0.70423086, 0.27746259, 0.85756069, 0.49824611,
       0.93069577])

In [19]:
np.random.randn(6)
# randn generates number ib between -3 & 3.

array([ 0.1702785 ,  0.51769533, -0.3867681 ,  0.91806516,  0.5762188 ,
        1.563991  ])

In [20]:
np.random.randint(10,20,7)

array([14, 10, 12, 17, 11, 17, 16], dtype=int32)

### **Array Attributes**

In [21]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.shape

(3, 3)

In [23]:
arr.size

9

In [24]:
arr.dtype

dtype('int64')

###  **Array Methods**

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.min()

np.int64(1)

In [27]:
arr.max()

np.int64(9)

In [28]:
arr.sum()

np.int64(45)

In [29]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [30]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [31]:
# For Row Axis=1
# For Column Axis=0

In [32]:
arr.mean()

np.float64(5.0)

In [33]:
arr.std()

np.float64(2.581988897471611)

In [34]:
arr.argmax()
# index of max 

np.int64(8)

In [35]:
arr.argmin()
# index of min

np.int64(0)

***Reshaping and Resizing***

In [36]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
arr=arr.reshape(5,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])