In [1]:
import numpy as np

### ***Numpy Indexing and Slicing of Vectors:-***

In [2]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[5]

np.int64(6)

In [11]:
# [2,3,4,5,6]
#arr[1:6]
arr[-9:-4]

array([2, 3, 4, 5, 6])

### ***Numpy Indexing and Slicing of Matrix:-***

In [13]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [16]:
arr[0]

array([1, 2, 3, 4, 5])

In [22]:
# print 1 only
arr[0,0]

np.int64(1)

In [21]:
# print 30 only
arr[5,4]

np.int64(30)

In [25]:
# Print 
# 2  3
# 7  8
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [26]:
# Print
#    19  20
#    24  25
#    29  30
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [27]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [30]:
# Print
#    3
#    8
#    13
#    18
#    23
#    28
arr[0:,2]

array([ 3,  8, 13, 18, 23, 28])

### ***Boolean Indexing:-***

In [35]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
bool_index= arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [37]:
arr=arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])