In [62]:
import numpy as np

### **Array Operation**

***Arithmetic Operation:-***

In [63]:
# the size of both array should be same for performing operation.
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

In [64]:
add=arr1+arr2
add

array([ 7,  9, 11, 13, 15])

In [65]:
sub=arr2-arr1
sub

array([5, 5, 5, 5, 5])

In [66]:
mul=arr1*arr2
mul

array([ 6, 14, 24, 36, 50])

In [67]:
div=arr2/arr1
div

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [68]:
fl_div=arr2//arr1
fl_div

array([6, 3, 2, 2, 2])

In [69]:
exp=arr1**arr2
exp

array([      1,     128,    6561,  262144, 9765625])

***Broadcasting:-***

In [70]:
l=[10,20,30,40,50]
arr=np.array(l)

In [71]:
# If we want to add 10 in every element in list we cant write l+10 but we can arr+10
arr+10

array([20, 30, 40, 50, 60])

In [72]:
arr=np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [73]:
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

***Deep and Shallow Copy:-***

In [74]:
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [75]:
slice=a[1:3]
slice
# Here slice is creaing different array so a is not changing.

array([2, 3])

In [76]:
b=a
b

array([1, 2, 3, 4, 5])

In [77]:
b[0]=99
b

array([99,  2,  3,  4,  5])

In [78]:
a
# Here a will change because of deep copy.

array([99,  2,  3,  4,  5])

In [79]:
# if we dont want to do this we can
b=a.copy()
b

array([99,  2,  3,  4,  5])

***Matrix Operation:-***

In [80]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [81]:
A

array([[1, 2],
       [3, 4]])

In [82]:
B

array([[5, 6],
       [7, 8]])

In [83]:
# For Matrix multiplication we use @.
A @ B

array([[19, 22],
       [43, 50]])

In [84]:
# For Transpose we use T
A.T

array([[1, 3],
       [2, 4]])

### **Advance Array Manipulation:-**

***Stacking Array:-***

In [85]:
A=np.array([[1,2,3,4]])
B=np.array([[5,6,7,8]])

In [86]:
np.vstack((A,B))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [87]:
np.hstack((A,B))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [88]:
np.column_stack((A,B))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

***Spliting Array:-***

In [89]:
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [90]:
np.hsplit(a,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [91]:
np.hsplit(a,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [92]:
np.vsplit(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [93]:
np.vsplit(a,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]